name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: 'recursive'
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: npm ci
      - run: npm run compile
      - run: git diff --exit-code
      - run: npm run test
