name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: npm ci
      - run: npm run compile
      - run: npm run test:erc721
      - run: npx prettier --list-different ./test/*.js
      - run: npx hardhat check
