name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: addnab/docker-run-action@v1
        with:
          image: trufflesuite/ganache-cli
          ports: 8545:8545
          run: ganache-cli -a 100
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache
        uses: actions/cache@v2.1.3    
        with:
          path: 'node_modules'
          key: hash-${{ hashFiles('package-lock.json') }}
      - name: install deps
        run: npm ci
      - name: truffle test
        run: npm test